In [105]:
import pandas as pd
import numpy as np

In [106]:
df = pd.read_csv('/Users/joelmathooko/Desktop/PROJECTS/Jumia Project/Excel_jumia_dataset.csv')

df.head()

,Product,Current price,old price,Discount,Review,Ratingd
0,115 Piece Set Of Multifunctional Precision Sc...,KSh 950,"KSh 1,525",38%,-2.0,4.5 out of 5
1,Metal Decorative Hooks Key Hangers Entryway Wa...,KSh 527,KSh 999,47%,-14.0,4.1 out of 5
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,"KSh 2,199","KSh 2,923",25%,-24.0,4.6 out of 5
3,Weighing Scale Digital Bathroom Body Fat Scale...,"KSh 1,580","KSh 2,499",37%,-7.0,4.7 out of 5
4,Portable Home Small Air Humidifier 3-Speed Fan...,"KSh 1,740","KSh 2,356",26%,-5.0,4.8 out of 5

In [107]:
df.shape

(115, 6)

In [108]:
df.columns

Index(['Product', 'Current price', 'old price', 'Discount', 'Review',
       'Ratingd'],
      dtype='object')

In [109]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [110]:
df.columns

Index(['product', 'current_price', 'old_price', 'discount', 'review',
       'ratingd'],
      dtype='object')

In [111]:
df = df.rename(columns={"ratingd": "rating"})

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product        115 non-null    object
 1   current_price  115 non-null    object
 2   old_price      115 non-null    object
 3   discount       115 non-null    object
 4   review         57 non-null     float64
 5   rating         57 non-null     object
dtypes: float64(1), object(5)
memory usage: 5.5+ KB

In [113]:
df.isna().sum()

product           0
current_price     0
old_price         0
discount          0
review           58
rating           58
dtype: int64

In [114]:
df["total_rating"] = (
    df["rating"]
    .str.extract(r"out of\s+(\d+)", expand=False)
    .astype("Int64")
)

df["rating"] = (
    df["rating"]
    .str.extract(r"(\d+(?:\.\d+)?)", expand=False)
    .astype(float)
)

In [115]:
df[["rating", "total_rating"]].head()

   rating  total_rating
0     4.5             5
1     4.1             5
2     4.6             5
3     4.7             5
4     4.8             5

In [116]:
for col in ["current_price", "old_price"]:
    prices = df[col].str.replace("KSh ", "").str.replace(",", "")
    
    df[f"{col}_min"] = prices.str.split(" - ").str[0].astype(float)
    df[f"{col}_max"] = prices.str.split(" - ").str[-1].astype(float)

In [117]:
df[
    [
        "current_price_min",
        "current_price_max",
        "old_price_min",
        "old_price_max"
    ]
].head()

   current_price_min  current_price_max  old_price_min  old_price_max
0              950.0              950.0         1525.0         1525.0
1              527.0              527.0          999.0          999.0
2             2199.0             2199.0         2923.0         2923.0
3             1580.0             1580.0         2499.0         2499.0
4             1740.0             1740.0         2356.0         2356.0

In [118]:
(
    (df["current_price_min"] > df["current_price_max"]).sum(),
    (df["old_price_min"] > df["old_price_max"]).sum()
)

(np.int64(0), np.int64(0))

In [119]:
df = df.drop(columns=["current_price", "old_price"])

In [120]:
df["discount"] = (
    df["discount"]
    .str.replace("%", "")
    .astype(float) / 100
)

In [121]:
df.select_dtypes(include="number").lt(0).sum()

discount              0
review               57
rating                0
total_rating          0
current_price_min     0
current_price_max     0
old_price_min         0
old_price_max         0
dtype: Int64

In [122]:
df["review"] = df["review"].abs()

In [123]:
df.select_dtypes(include="number").lt(0).sum()

discount             0
review               0
rating               0
total_rating         0
current_price_min    0
current_price_max    0
old_price_min        0
old_price_max        0
dtype: Int64

In [124]:
df.isna().sum()

product               0
discount              0
review               58
rating               58
total_rating         58
current_price_min     0
current_price_max     0
old_price_min         0
old_price_max         0
dtype: int64

In [125]:
df.duplicated().sum()

np.int64(3)

In [126]:
df[df.duplicated(keep=False)].sort_values("product")

,product,discount,review,rating,total_rating,current_price_min,current_price_max,old_price_min,old_price_max
95,6 Layers Steel Pipe Assembling Dustproof Stora...,0.47,NaN,NaN,<NA>,899.0,899.0,1699.0,1699.0
96,6 Layers Steel Pipe Assembling Dustproof Stora...,0.47,NaN,NaN,<NA>,899.0,899.0,1699.0,1699.0
42,"Balloon Insert, Birthday Party Balloon Set, PU...",0.42,NaN,NaN,<NA>,610.0,610.0,1060.0,1060.0
43,"Balloon Insert, Birthday Party Balloon Set, PU...",0.42,NaN,NaN,<NA>,610.0,610.0,1060.0,1060.0
84,"Balloon Insert, Birthday Party Balloon Set, PU...",0.42,NaN,NaN,<NA>,610.0,610.0,1060.0,1060.0

In [127]:
df = df.drop_duplicates()

In [128]:
df = df.reset_index(drop=True)

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product            112 non-null    object
 1   discount           112 non-null    float64
 2   review             57 non-null     float64
 3   rating             57 non-null     float64
 4   total_rating       57 non-null     Int64
 5   current_price_min  112 non-null    float64
 6   current_price_max  112 non-null    float64
 7   old_price_min      112 non-null    float64
 8   old_price_max      112 non-null    float64
dtypes: Int64(1), float64(7), object(1)
memory usage: 8.1+ KB

In [130]:
df.isna().sum()

product               0
discount              0
review               55
rating               55
total_rating         55
current_price_min     0
current_price_max     0
old_price_min         0
old_price_max         0
dtype: int64

In [131]:
df.select_dtypes(include="number").lt(0).sum()

discount             0
review               0
rating               0
total_rating         0
current_price_min    0
current_price_max    0
old_price_min        0
old_price_max        0
dtype: Int64

In [132]:
df["current_price_mid"] = (
    df["current_price_min"] + df["current_price_max"]
) / 2

df["old_price_mid"] = (
    df["old_price_min"] + df["old_price_max"]
) / 2

df["discount_amount"] = (
    df["old_price_mid"] - df["current_price_mid"]
)

In [133]:
df[[
    "product",
    "current_price_mid",
    "old_price_mid",
    "discount_amount",
    "discount"
]].head(10)

,product,current_price_mid,old_price_mid,discount_amount,discount
0,115 Piece Set Of Multifunctional Precision Sc...,950.0,1525.0,575.0,0.38
1,Metal Decorative Hooks Key Hangers Entryway Wa...,527.0,999.0,472.0,0.47
2,Portable Mini Cordless Car Vacuum Cleaner - Blue,2199.0,2923.0,724.0,0.25
3,Weighing Scale Digital Bathroom Body Fat Scale...,1580.0,2499.0,919.0,0.37
4,Portable Home Small Air Humidifier 3-Speed Fan...,1740.0,2356.0,616.0,0.26
5,220V 60W Electric Soldering Iron Kits With Too...,2999.0,3290.0,291.0,0.09
6,137 Pieces Cake Decorating Tool Set Baking Sup...,2319.0,3032.0,713.0,0.24
7,Desk Foldable Fan Adjustable Fan Strong Wind 3...,988.0,1580.0,592.0,0.37
8,LASA FOLDING TABLE SERVING STAND,1274.0,2800.0,1526.0,0.55
9,13 In 1 Home Repair Tools Box Kit Set,1600.0,2929.0,1329.0,0.45

In [134]:
df["calculated_discount_pct"] = (
    df["discount_amount"] / df["old_price_mid"]
)

df["discount_difference"] = (
    df["calculated_discount_pct"] - df["discount"]
)

df["discount_difference"].describe()

count    112.000000
mean      -0.000627
std        0.005240
min       -0.046667
25%       -0.002735
50%        0.000000
75%        0.002015
max        0.004925
Name: discount_difference, dtype: float64

In [135]:
df.loc[
    df["discount_difference"].abs() > 0.02,
    [
        "product",
        "current_price_mid",
        "old_price_mid",
        "discount_amount",
        "discount",
        "calculated_discount_pct",
        "discount_difference"
    ]
]

,product,current_price_mid,old_price_mid,discount_amount,discount,calculated_discount_pct,discount_difference
38,"1/2/3 Seater Elastic Sofa Cover,Living Room/Ho...",1800.0,2700.0,900.0,0.38,0.333333,-0.046667

In [136]:
df["rating_category"] = np.select(
    [
        df["rating"] < 3,
        df["rating"] <= 4.5,
        df["rating"] > 4.5
    ],
    [
        "Poor",
        "Average",
        "Excellent"
    ],
    default="Missing"
)

In [137]:
df["rating_category"].value_counts(dropna=False)

rating_category
Missing      55
Average      26
Excellent    19
Poor         12
Name: count, dtype: int64

In [138]:
df["discount_category"] = np.select(
    [
        df["discount"] < 0.20,
        df["discount"] <= 0.40,
        df["discount"] > 0.40
    ],
    [
        "Low",
        "Medium",
        "High"
    ],
    default="Unknown"
)

In [139]:
df["discount_category"].value_counts()

discount_category
High      62
Medium    32
Low       18
Name: count, dtype: int64

In [ ]:
median_price = df["current_price_mid"].median()

print(median_price)

NameError: name 'xdf' is not defined

In [ ]:
df.to_csv("jumia_products_cleaned.csv", index=False)

In [ ]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.9.12)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/joelmathooko/Library/Python/3.10/lib/python/site-packages (from sqlalchemy) (4.16.0)

In [ ]:
from sqlalchemy import create_engine, text

In [ ]:
from db_connection import engine

In [ ]:
with engine.connect() as conn:
    result = conn.execute(
        text("SELECT current_user, current_database()")
    )
    print(result.fetchone())

('joelmathooko', 'jumia_products')

In [ ]:
df.to_sql(
    "products",
    engine,
    if_exists="replace",
    index=False
)

112

In [ ]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM products"))
    print(result.scalar())

112

In [ ]:
df[["discount", "review"]].corr()

          discount    review
discount  1.000000 -0.136823
review   -0.136823  1.000000

In [ ]:
df[["rating", "review"]].corr()

          rating    review
rating  1.000000  0.057209
review  0.057209  1.000000

In [ ]:
df[["current_price_mid", "rating"]].corr()

                   current_price_mid   rating
current_price_mid            1.00000  0.11009
rating                       0.11009  1.00000

In [ ]:
#Relationship	Correlation	Interpretation
#Rating ↔ Reviews	0.057	Almost no relationship
#Price ↔ Rating	0.110	Very weak positive relationship